apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yegli/kubecon-demo.git
    targetRevision: "master"
    path: "sample-app-1"
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
